spring.application.name=apigateway
server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Account Service
spring.cloud.gateway.server.webflux.routes[0].id=account-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://ACCOUNT-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/accounts/**

# Auth Service
spring.cloud.gateway.server.webflux.routes[1].id=auth-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://AUTHSERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/auth/**
logging.level.org.springframework.cloud.gateway=DEBUG

spring.cloud.gateway.server.webflux.routes[2].id=transaction-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://TRANSACTION-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/transactions/**

# Settlement Service
spring.cloud.gateway.server.webflux.routes[3].id=settlement-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://SETTLEMENT-SERVICE
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/settlements/**

# Reconciliation Service
spring.cloud.gateway.server.webflux.routes[4].id=reconciliation-service
spring.cloud.gateway.server.webflux.routes[4].uri=lb://RECONCILIATION-SERVICE
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/reconciliations/**

logging.level.org.springframework.cloud.gateway=DEBUG